

datasource:
  username: root
  password: 12341234
  driver-class-name: org.mariadb.jdbc.Driver
  url: jdbc:mariadb://database-1.cvyclyh4jg14.ap-northeast-2.rds.amazonaws.com:3306/food_place_project
  jpa:
    show-sql: true

spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher


jwtpassword:
  source: cheerupBE1

logging:
  level:
    org.hibernate.SQL: debug
server:
  port: 8079